name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Windows build job
  build-windows:
    runs-on: windows-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
  
    - name: Install dependencies via vcpkg
      run: |
        .\vcpkg\vcpkg install --triplet x64-windows
        .\vcpkg\vcpkg integrate install
  
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release
  
    - name: Build project
      run: cmake --build build --config Release

    # Novo passo para copiar a glfw3.dll para o diretório Release
    - name: Copy glfw3.dll to Release
      run: |
        copy .\vcpkg_installed\x64-windows\bin\glfw3.dll build\Release\

    - name: List build directory
      run: dir build\Release
  
    # Atualizando o upload para incluir tanto o executável quanto a glfw3.dll
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hexspanned-windows
        path: |
          build\Release\hexspanned.exe
          build\Release\glfw3.dll  # Incluindo a glfw3.dll no artefato
