name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install required system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
      id: vcpkg

    - name: Install dependencies via vcpkg
      run: |
        ./vcpkg/vcpkg install --triplet x64-linux
        ./vcpkg/vcpkg integrate install

    - name: Configure CMake
      run: cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build project
      run: cmake --build build

    - name: Run tests (if applicable)
      run: ctest --output-on-failure
      working-directory: build

    # Step to upload the compiled artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hexspanned-executable
        path: build/hexspanned
